//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EE4WebCam.ServiciosWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosCamaraSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosCamara : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidarUsuarioCSharpOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerCamarasDisponiblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerTiempoVideoOperationCompleted;
        
        private System.Threading.SendOrPostCallback grabarEnCamaraOperationCompleted;
        
        private System.Threading.SendOrPostCallback subirVideoLogicoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosCamara() {
            this.Url = global::EE4WebCam.Properties.Settings.Default.EE4WebCam_ServiciosWeb_ServiciosCamara;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidarUsuarioCSharpCompletedEventHandler ValidarUsuarioCSharpCompleted;
        
        /// <remarks/>
        public event ObtenerCamarasDisponiblesCompletedEventHandler ObtenerCamarasDisponiblesCompleted;
        
        /// <remarks/>
        public event obtenerTiempoVideoCompletedEventHandler obtenerTiempoVideoCompleted;
        
        /// <remarks/>
        public event grabarEnCamaraCompletedEventHandler grabarEnCamaraCompleted;
        
        /// <remarks/>
        public event subirVideoLogicoCompletedEventHandler subirVideoLogicoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarUsuarioCSharp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidarUsuarioCSharp(string username, string password) {
            object[] results = this.Invoke("ValidarUsuarioCSharp", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarUsuarioCSharpAsync(string username, string password) {
            this.ValidarUsuarioCSharpAsync(username, password, null);
        }
        
        /// <remarks/>
        public void ValidarUsuarioCSharpAsync(string username, string password, object userState) {
            if ((this.ValidarUsuarioCSharpOperationCompleted == null)) {
                this.ValidarUsuarioCSharpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarUsuarioCSharpOperationCompleted);
            }
            this.InvokeAsync("ValidarUsuarioCSharp", new object[] {
                        username,
                        password}, this.ValidarUsuarioCSharpOperationCompleted, userState);
        }
        
        private void OnValidarUsuarioCSharpOperationCompleted(object arg) {
            if ((this.ValidarUsuarioCSharpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarUsuarioCSharpCompleted(this, new ValidarUsuarioCSharpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCamarasDisponibles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerCamarasDisponibles() {
            object[] results = this.Invoke("ObtenerCamarasDisponibles", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerCamarasDisponiblesAsync() {
            this.ObtenerCamarasDisponiblesAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerCamarasDisponiblesAsync(object userState) {
            if ((this.ObtenerCamarasDisponiblesOperationCompleted == null)) {
                this.ObtenerCamarasDisponiblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCamarasDisponiblesOperationCompleted);
            }
            this.InvokeAsync("ObtenerCamarasDisponibles", new object[0], this.ObtenerCamarasDisponiblesOperationCompleted, userState);
        }
        
        private void OnObtenerCamarasDisponiblesOperationCompleted(object arg) {
            if ((this.ObtenerCamarasDisponiblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerCamarasDisponiblesCompleted(this, new ObtenerCamarasDisponiblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/obtenerTiempoVideo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int obtenerTiempoVideo() {
            object[] results = this.Invoke("obtenerTiempoVideo", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerTiempoVideoAsync() {
            this.obtenerTiempoVideoAsync(null);
        }
        
        /// <remarks/>
        public void obtenerTiempoVideoAsync(object userState) {
            if ((this.obtenerTiempoVideoOperationCompleted == null)) {
                this.obtenerTiempoVideoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerTiempoVideoOperationCompleted);
            }
            this.InvokeAsync("obtenerTiempoVideo", new object[0], this.obtenerTiempoVideoOperationCompleted, userState);
        }
        
        private void OnobtenerTiempoVideoOperationCompleted(object arg) {
            if ((this.obtenerTiempoVideoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerTiempoVideoCompleted(this, new obtenerTiempoVideoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/grabarEnCamara", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void grabarEnCamara(string nombrecamara) {
            this.Invoke("grabarEnCamara", new object[] {
                        nombrecamara});
        }
        
        /// <remarks/>
        public void grabarEnCamaraAsync(string nombrecamara) {
            this.grabarEnCamaraAsync(nombrecamara, null);
        }
        
        /// <remarks/>
        public void grabarEnCamaraAsync(string nombrecamara, object userState) {
            if ((this.grabarEnCamaraOperationCompleted == null)) {
                this.grabarEnCamaraOperationCompleted = new System.Threading.SendOrPostCallback(this.OngrabarEnCamaraOperationCompleted);
            }
            this.InvokeAsync("grabarEnCamara", new object[] {
                        nombrecamara}, this.grabarEnCamaraOperationCompleted, userState);
        }
        
        private void OngrabarEnCamaraOperationCompleted(object arg) {
            if ((this.grabarEnCamaraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.grabarEnCamaraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/subirVideoLogico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void subirVideoLogico(string nombrearchivo) {
            this.Invoke("subirVideoLogico", new object[] {
                        nombrearchivo});
        }
        
        /// <remarks/>
        public void subirVideoLogicoAsync(string nombrearchivo) {
            this.subirVideoLogicoAsync(nombrearchivo, null);
        }
        
        /// <remarks/>
        public void subirVideoLogicoAsync(string nombrearchivo, object userState) {
            if ((this.subirVideoLogicoOperationCompleted == null)) {
                this.subirVideoLogicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubirVideoLogicoOperationCompleted);
            }
            this.InvokeAsync("subirVideoLogico", new object[] {
                        nombrearchivo}, this.subirVideoLogicoOperationCompleted, userState);
        }
        
        private void OnsubirVideoLogicoOperationCompleted(object arg) {
            if ((this.subirVideoLogicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.subirVideoLogicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ValidarUsuarioCSharpCompletedEventHandler(object sender, ValidarUsuarioCSharpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarUsuarioCSharpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarUsuarioCSharpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerCamarasDisponiblesCompletedEventHandler(object sender, ObtenerCamarasDisponiblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerCamarasDisponiblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerCamarasDisponiblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void obtenerTiempoVideoCompletedEventHandler(object sender, obtenerTiempoVideoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerTiempoVideoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerTiempoVideoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void grabarEnCamaraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void subirVideoLogicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591